const path=require("node:path");
// console.log(__dirname);
// console.log(__filename);
// console.log("folder name=",path.basename(__dirname));
// console.log("file name=",path.basename(__filename));
// console.log("extension=",path.extname(__filename));
// console.log(path.parse(__filename));
// console.log(path.format(path.parse(__filename)));
// console.log(path.isAbsolute(__filename));
// console.log(path.isAbsolute('./data.json'));
// console.log(path.join("folder1","folder2","index.html"));
// console.log(path.join("/folder1","folder2","index.html"));
// console.log(path.join("/folder1","//folder2","index.html"));
// console.log(path.join("/folder1","//folder2","../index.html"));
// console.log(path.join(__dirname,"data.json"));
console.log('###################################');
console.log(path.resolve("folder1","folder2","index.html"));
console.log(path.resolve("/folder1","folder2","index.html"));
console.log(path.resolve("/folder1","//folder2","index.html"));
console.log(path.resolve("/folder1","//folder2","../index.html"));
console.log(path.resolve(__dirname,"data.json"));
console.log('###################################');
console.log(path.resolve(__dirname, "path"));
console.log(path.resolve(__dirname, "/path"));
console.log(path.resolve(__dirname, "./path"));
console.log(path.resolve(__dirname, "../path"));